import { Report } from './types';

export const SEED_REPORTS: Report[] = [
  {
    id: 'report-1',
    category: 'lost',
    petName: 'Max',
    breed: 'Golden Retriever Mix',
    gender: 'macho',
    size: 'grande',
    color: 'Dorado',
    description: 'Max se escapó del jardín trasero por la tarde. Llevaba un collar azul con placa en forma de hueso, pero no tiene número de teléfono. Es muy amigable pero asustadizo con ruidos fuertes. Si lo ves, por favor no corras hacia él, ofrécele algo de comida.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGJUE72ORcUSuPhBGfknJhDnO60FRShQQkH6cBixFaOBXMs5hXvH75sCfFfIp9vhP8lqLPaBLCK7AarxebNwuAE_6N3J8VZ_Hw0TM7d5gdYMdONr5DumeRH9a1Xwyy2Zh8C2vMnt5wvdYKurh_EjFPTgNCpT4U1Tvqc1RRqIkaRfa5kz7Xr1EzIwCuk4YRh0nqxeqhyP88Cs20ZAXjlbwhFqZIt2Zk07rzA_8wnwQyximG8CsgW3ZySeHApS2moyl0N0lQRu5ec0w',
    date: 'Hoy',
    timeAgo: 'Hace 2 horas',
    locationName: 'Parque de las Esculturas, Providencia',
    lat: -33.4244,
    lng: -70.6156,
    reporterName: 'Laura G.',
    reporterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB_GsYrFvdnNCQ-1YMwmqmsUkgNYCJO3evbepJWaoe_V_riLSszLj_4x-CJVVyvnNSPWc7MFk7p-X870GjzGYeDUOZD8a7yu_rjLijKaLS0zD7kSCUtskaMJvH4QGDqN9PLxPw8r72PJxQpEpecfXaQhSyhJfxX19l1BZhv9mP3mLqLPB3K_EJL8NnJkqv_Qyy8QZ70Wb5B3hBnJsPnXMLO5NpxnmgjRJtgrSxfWttRURtcuOictHDRbyxeJSfyj6-4gRlvLdNtnaA',
    reporterPhone: '+56 9 1234 5678',
    isVerifiedUser: true,
    views: 124,
    status: 'activo'
  },
  {
    id: 'report-2',
    category: 'spotted',
    petName: 'Michi',
    breed: 'Gato Común Atigrado',
    gender: 'desconocido',
    size: 'pequeño',
    color: 'Naranja Atigrado',
    description: 'Posible coincidencia: Gato atigrado sentado en la barda de un condominio, parece algo desorientado pero en buen estado físico. Trae un cascabel verde en el cuello.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOOmBdaHGbdYKCb2hXOv4UxdHPrDbjBLw9i19fQ0WGAWwwuNgfHJlugPi403vCcaDktJpXCwAtGK-wxlpKEAcsZdfdlqQBFj6VCyFhxjveTH9fRg5YLzajxbuUPFm3o5E1ZNEU7mVmqTD9k-DikqePXZpMy-UOdbEyPZAUqFEEFVZTaxtFP1EgNamWJctRZF85XSRTqp94DVSsXH_54a41OAucLUSvyRe73v8_KcDTk_hgMzY3zL0eEb0oQeBXKMvuse9oiIWDRkE',
    date: 'Hoy',
    timeAgo: 'Hace 42 min',
    locationName: 'Paseo Huérfanos con Bandera, Santiago Centro',
    lat: -33.4402,
    lng: -70.6533,
    reporterName: 'Carlos M.',
    reporterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKykiGUmBdGBXUes7OPkUNwk2nXXIOOkYBKn0P7WH8yuZwiiCITP2J79TUnD1qHPZj-o0IYKB5lcga_Pg27TfjgBDXIEAxXTwjkytHKczPx7ELb2qALK94M496pLmFj85_xwgOxddk3ECOIOoQ-8YwY1jA2nFPoPtf29wkZzIYcsuqb4J_KQfDgjeQjgi3o_yc9pr25nkCMtfx3B1fiHqrlpJfmUY3G_tSY9MgNVpngTx3kjwH7ScrPSnEDN8MYzSeEKRqmggxdNM',
    reporterPhone: '+56 9 8765 4321',
    isVerifiedUser: false,
    views: 48,
    status: 'activo'
  },
  {
    id: 'report-3',
    category: 'stray',
    breed: 'Mestizo Scruffy',
    gender: 'macho',
    size: 'mediano',
    color: 'Gris y Blanco',
    description: 'Un hermoso perro mestizo, algo sucio y tímido, deambulando cerca de botes de basura. Los vecinos le pusimos agua pero tiene miedo de acercarse.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBj5JJDAGFKzhdnLwFBGBPZQs1ARLPCR-3wPe3NFp9CCaek1M8Q2eIra7zp-S-EwzJT4HZMqQMmKuBkdvpiROrhwcHbzlVExE3-ZO7NZ2VeP0yapGAjrQnnDS7ASKMMTjmRabSTz3Ob_TPKSQiTj2RWQ8C9eEDsuce_Mc81Y6Es-9FnvVAY-OcJk8P2nuCdwRBkKlGOjVbR2mYodzXgvbCUlcCTSv_kNmpMbb72kBOBfl6TFNqnlPVxucVM9LCiXWyPbzPwCQUHJGg',
    date: 'Ayer',
    timeAgo: 'Ayer, 18:30',
    locationName: 'Plaza Ñuñoa, Ñuñoa',
    lat: -33.4542,
    lng: -70.5975,
    reporterName: 'Vecinos Unidos',
    reporterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEEWdQCzD_wWyBEyMxfb9J66fvihuBcbRnanbLpiynMIS-7BIBUZ9-DAa0JnpuqljPgKiS9zkxkw2OuT4dcB8kyIrn2nd4BPqGTUZZ1U61pCpfrxaZySXdjWyfTjVYgri7iWS6vbs2oljqTfxVbGNApv8mlGflTJ73ZTD-2wOijxdYYwo_HPTFaE23OG-EqxG2X8DgaGyj_vTJmGlr3g3sAFFcTThVz8Vl8X5ojQbiDcT8wdohUVwCazW0qFjBxewYgmHtNMsW11M',
    reporterPhone: '+56 9 9999 8888',
    isVerifiedUser: false,
    views: 92,
    status: 'activo'
  },
  {
    id: 'report-4',
    category: 'danger',
    description: '¡¡Atención!! Se reportó posible veneno en el Parque Araucano entre los arbustos de la zona de juegos. Favor de cuidar a sus mascotas y no dejarlas sueltas.',
    image: '',
    date: 'Ayer',
    timeAgo: 'Ayer, 14:15',
    locationName: 'Parque Araucano, Las Condes',
    lat: -33.4026,
    lng: -70.5794,
    reporterName: 'Mascosafe Oficial',
    reporterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKykiGUmBdGBXUes7OPkUNwk2nXXIOOkYBKn0P7WH8yuZwiiCITP2J79TUnD1qHPZj-o0IYKB5lcga_Pg27TfjgBDXIEAxXTwjkytHKczPx7ELb2qALK94M496pLmFj85_xwgOxddk3ECOIOoQ-8YwY1jA2nFPoPtf29wkZzIYcsuqb4J_KQfDgjeQjgi3o_yc9pr25nkCMtfx3B1fiHqrlpJfmUY3G_tSY9MgNVpngTx3kjwH7ScrPSnEDN8MYzSeEKRqmggxdNM',
    reporterPhone: '133',
    isVerifiedUser: true,
    views: 245,
    status: 'activo'
  }
];
